In [56]:
import json
import pandas as pd
from IPython.display import Image, JSON, display
from run_main import run

The strucure of an evolved model can be examined because all the parameters are stored in a readable JSON format configuration file. First, set the folder that contains the JSON file:

In [57]:
origFolderName="notebooks/example_W2D18L"
outputFolderName=origFolderName + "_modified"

Load the JSON file. Every time a simulation or evoltution is performed the new evolved parameters and worm states are rewritten to the JSON file, which will therefore need to be reloaded:

In [58]:
with open(origFolderName + '/worm_data_worm.json') as json_file:
    json_data = json.load(json_file)

The full expandable JSON can be examined.

In [59]:
JSON(json_data)

The "nervous_system" field contains several sub-fields.

In [60]:
pd.DataFrame({"nervous_system keys": json_data["nervous_system"].keys()})

    nervous_system keys
0            cell_names
1  cell_names_no_suffix
2                 cells
3        chemical_conns
4      electrical_conns
5            model_name

The "cell_names" field contains the list of nervous system cells.

In [6]:
print(json_data['nervous_system']['cell_names']['value'])

['DB_0', 'DD_0', 'VBA_0', 'VDA_0', 'VBP_0', 'VDP_0', 'DB_1', 'DD_1', 'VBA_1', 'VDA_1', 'VBP_1', 'VDP_1', 'DB_2', 'DD_2', 'VBA_2', 'VDA_2', 'VBP_2', 'VDP_2', 'DB_3', 'DD_3', 'VBA_3', 'VDA_3', 'VBP_3', 'VDP_3', 'DB_4', 'DD_4', 'VBA_4', 'VDA_4', 'VBP_4', 'VDP_4', 'DB_5', 'DD_5', 'VBA_5', 'VDA_5', 'VBP_5', 'VDP_5', 'SMDD_0', 'RMDD_0', 'SMDV_0', 'RMDV_0']

The "chemical_conns" and "electrical_conns" fields contain the list of connections between nervous system cells.

In [7]:
print(json_data['nervous_system']['chemical_conns']['value'])

[{'from': 'DB_0', 'to': 'DB_0', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'DD_0', 'to': 'DD_0', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'DB_0', 'to': 'DD_0', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'VBA_0', 'to': 'DD_0', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 3.7242620902827905}}, {'from': 'VBP_0', 'to': 'DD_0', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 3.7242620902827905}}, {'from': 'VBA_0', 'to': 'VBA_0', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'VDA_0', 'to': 'VDA_0', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'VBA_0', 'to': 'VDA_0', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'DB_0', 'to': 'VDA_0', 'weight': {'evotag': 8, 'value': 7.448524180565581}}, {'from': 'DD_0', 'to': 'VDA_0', 'weight': {'evotag': 9, 'value': 14.734094612984334}}, {'from': 'VBP_0', 'to': 'VBP_0', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'VDP_0', 'to': 'VDP_0', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'VBP_0', 'to': 'VDP_0', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'DB_0', 'to': 'VDP_0', 'weight': {'evotag': 8, 'value': 7.448524180565581}}, {'from': 'DB_1', 'to': 'DB_1', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'DD_1', 'to': 'DD_1', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'DB_1', 'to': 'DD_1', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'VBA_1', 'to': 'DD_1', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 3.7242620902827905}}, {'from': 'VBP_1', 'to': 'DD_1', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 3.7242620902827905}}, {'from': 'VBA_1', 'to': 'VBA_1', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'VDA_1', 'to': 'VDA_1', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'VBA_1', 'to': 'VDA_1', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'DB_1', 'to': 'VDA_1', 'weight': {'evotag': 8, 'value': 7.448524180565581}}, {'from': 'DD_1', 'to': 'VDA_1', 'weight': {'evotag': 9, 'value': 14.734094612984334}}, {'from': 'VBP_1', 'to': 'VBP_1', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'VDP_1', 'to': 'VDP_1', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'VBP_1', 'to': 'VDP_1', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'DB_1', 'to': 'VDP_1', 'weight': {'evotag': 8, 'value': 7.448524180565581}}, {'from': 'DB_2', 'to': 'DB_2', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'DD_2', 'to': 'DD_2', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'DB_2', 'to': 'DD_2', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'VBA_2', 'to': 'DD_2', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 3.7242620902827905}}, {'from': 'VBP_2', 'to': 'DD_2', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 3.7242620902827905}}, {'from': 'VBA_2', 'to': 'VBA_2', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'VDA_2', 'to': 'VDA_2', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'VBA_2', 'to': 'VDA_2', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'DB_2', 'to': 'VDA_2', 'weight': {'evotag': 8, 'value': 7.448524180565581}}, {'from': 'DD_2', 'to': 'VDA_2', 'weight': {'evotag': 9, 'value': 14.734094612984334}}, {'from': 'VBP_2', 'to': 'VBP_2', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'VDP_2', 'to': 'VDP_2', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'VBP_2', 'to': 'VDP_2', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'DB_2', 'to': 'VDP_2', 'weight': {'evotag': 8, 'value': 7.448524180565581}}, {'from': 'DB_3', 'to': 'DB_3', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'DD_3', 'to': 'DD_3', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'DB_3', 'to': 'DD_3', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'VBA_3', 'to': 'DD_3', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 3.7242620902827905}}, {'from': 'VBP_3', 'to': 'DD_3', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 3.7242620902827905}}, {'from': 'VBA_3', 'to': 'VBA_3', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'VDA_3', 'to': 'VDA_3', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'VBA_3', 'to': 'VDA_3', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'DB_3', 'to': 'VDA_3', 'weight': {'evotag': 8, 'value': 7.448524180565581}}, {'from': 'DD_3', 'to': 'VDA_3', 'weight': {'evotag': 9, 'value': 14.734094612984334}}, {'from': 'VBP_3', 'to': 'VBP_3', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'VDP_3', 'to': 'VDP_3', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'VBP_3', 'to': 'VDP_3', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'DB_3', 'to': 'VDP_3', 'weight': {'evotag': 8, 'value': 7.448524180565581}}, {'from': 'DB_4', 'to': 'DB_4', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'DD_4', 'to': 'DD_4', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'DB_4', 'to': 'DD_4', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'VBA_4', 'to': 'DD_4', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 3.7242620902827905}}, {'from': 'VBP_4', 'to': 'DD_4', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 3.7242620902827905}}, {'from': 'VBA_4', 'to': 'VBA_4', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'VDA_4', 'to': 'VDA_4', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'VBA_4', 'to': 'VDA_4', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'DB_4', 'to': 'VDA_4', 'weight': {'evotag': 8, 'value': 7.448524180565581}}, {'from': 'DD_4', 'to': 'VDA_4', 'weight': {'evotag': 9, 'value': 14.734094612984334}}, {'from': 'VBP_4', 'to': 'VBP_4', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'VDP_4', 'to': 'VDP_4', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'VBP_4', 'to': 'VDP_4', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'DB_4', 'to': 'VDP_4', 'weight': {'evotag': 8, 'value': 7.448524180565581}}, {'from': 'DB_5', 'to': 'DB_5', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'DD_5', 'to': 'DD_5', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'DB_5', 'to': 'DD_5', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'VBA_5', 'to': 'DD_5', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 3.7242620902827905}}, {'from': 'VBP_5', 'to': 'DD_5', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 3.7242620902827905}}, {'from': 'VBA_5', 'to': 'VBA_5', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'VDA_5', 'to': 'VDA_5', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'VBA_5', 'to': 'VDA_5', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'DB_5', 'to': 'VDA_5', 'weight': {'evotag': 8, 'value': 7.448524180565581}}, {'from': 'DD_5', 'to': 'VDA_5', 'weight': {'evotag': 9, 'value': 14.734094612984334}}, {'from': 'VBP_5', 'to': 'VBP_5', 'weight': {'evotag': 5, 'value': -6.681587314056824}}, {'from': 'VDP_5', 'to': 'VDP_5', 'weight': {'evotag': 6, 'value': -2.8438626078194695}}, {'from': 'VBP_5', 'to': 'VDP_5', 'weight': {'evotag': 7, 'value': 2.289999938784325}}, {'from': 'DB_5', 'to': 'VDP_5', 'weight': {'evotag': 8, 'value': 7.448524180565581}}, {'from': 'SMDD_0', 'to': 'SMDD_0', 'weight': {'evotag': 21, 'value': -13.341395527065076}}, {'from': 'SMDV_0', 'to': 'SMDD_0', 'weight': {'evotag': 23, 'value': 0.0647450414472433}}, {'from': 'RMDD_0', 'to': 'RMDD_0', 'weight': {'evotag': 22, 'value': 4.77567055460183}}, {'from': 'SMDV_0', 'to': 'RMDD_0', 'weight': {'evotag': 24, 'value': 14.680980983477706}}, {'from': 'RMDV_0', 'to': 'RMDD_0', 'weight': {'evotag': 25, 'value': -13.660925307341254}}, {'from': 'SMDV_0', 'to': 'SMDV_0', 'weight': {'evotag': 21, 'value': -13.341395527065076}}, {'from': 'SMDD_0', 'to': 'SMDV_0', 'weight': {'evotag': 23, 'value': 0.0647450414472433}}, {'from': 'RMDV_0', 'to': 'RMDV_0', 'weight': {'evotag': 22, 'value': 4.77567055460183}}, {'from': 'SMDD_0', 'to': 'RMDV_0', 'weight': {'evotag': 24, 'value': 14.680980983477706}}, {'from': 'RMDD_0', 'to': 'RMDV_0', 'weight': {'evotag': 25, 'value': -13.660925307341254}}]

Connections contain the "from" and "to" cells and the "weight" value. This particular connection also contains the "evotag" field which means its value is not fixed, but is to be optimized if the evolutionary algorithm is executed (see below.) This particular connection also contains the "mfunc" field. This allows a function (here a function indexed by f_ind) to be called on the value before it used to set up the worm simulation (see below.)

In [8]:
print(json_data['nervous_system']['chemical_conns']['value'][3])

{'from': 'VBA_0', 'to': 'DD_0', 'weight': {'evotag': 8, 'mfunc': {'f_ind': 1, 'fact': 0.5}, 'value': 3.7242620902827905}}

The "nervous_system", "cells" field contains the parameters specific to the particular cell. The cell model used here has 'bias', 'gain' and 'tau' parameters. The last value of the dynamical 'state' is also included. The "cell_class" is mainly used for plotting. The 'bias' parameter also includes the 'evotag' field meaning it is not fixed if an optimization is performed (see below.)

In [9]:
print(json.dumps(json_data['nervous_system']['cells']['DB_0'], indent=2))

{
  "bias": {
    "evotag": 1,
    "value": 0.9188885838494046
  },
  "cell_class": {
    "value": "vnc"
  },
  "gain": {
    "value": 1.0
  },
  "state": {
    "value": 0.013888888888888888
  },
  "tau": {
    "evotag": 3,
    "value": 0.6390854137857667
  }
}

In [10]:
print(json.dumps(json_data['nervous_system']['cells']['VDA_1'], indent=2))

{
  "bias": {
    "evotag": 2,
    "value": -10.50067914566957
  },
  "cell_class": {
    "value": "vnc"
  },
  "gain": {
    "value": 1.0
  },
  "state": {
    "value": 0.2638888888888889
  },
  "tau": {
    "evotag": 4,
    "value": 0.6952001934027146
  }
}

The JSON configuration file contains all the worm parameters. For example, the stretch receptors contain the weights to and from body segments and to and from the nervous sytem:

In [61]:
pd.DataFrame({"stretch receptor keys": json_data["stretch_receptor"].keys()})

   stretch receptor keys
0              d_weights
1                 n_segs
2              n_stretch
3           ns_d_weights
4           ns_v_weights
5              plot_size
6           sr_head_gain
7             sr_head_sr
8            sr_vnc_gain
9              sr_vnc_sr
10                  type
11             v_weights

Weights from body segments to dorsal stretch receptors:

In [12]:
print(json.dumps(json_data['stretch_receptor']['d_weights']))

{"message": "Weights from body segments to dorsal SR", "value": [{"from_seg": 7, "to_sr": 1, "weight": {"value": -9.16958372306238}}, {"from_seg": 8, "to_sr": 1, "weight": {"value": -9.16958372306238}}, {"from_seg": 9, "to_sr": 1, "weight": {"value": -9.16958372306238}}, {"from_seg": 10, "to_sr": 1, "weight": {"value": -9.16958372306238}}, {"from_seg": 11, "to_sr": 1, "weight": {"value": -9.16958372306238}}, {"from_seg": 12, "to_sr": 1, "weight": {"value": -9.16958372306238}}, {"from_seg": 13, "to_sr": 1, "weight": {"value": -9.16958372306238}}, {"from_seg": 14, "to_sr": 1, "weight": {"value": -9.16958372306238}}, {"from_seg": 15, "to_sr": 1, "weight": {"value": -9.16958372306238}}, {"from_seg": 16, "to_sr": 1, "weight": {"value": -9.16958372306238}}, {"from_seg": 17, "to_sr": 1, "weight": {"value": -9.16958372306238}}, {"from_seg": 18, "to_sr": 1, "weight": {"value": -9.16958372306238}}, {"from_seg": 19, "to_sr": 1, "weight": {"value": -9.16958372306238}}, {"from_seg": 20, "to_sr": 1, "weight": {"value": -9.16958372306238}}, {"from_seg": 7, "to_sr": 2, "weight": {"value": -26.801559194455454}}, {"from_seg": 8, "to_sr": 2, "weight": {"value": -26.801559194455454}}, {"from_seg": 9, "to_sr": 2, "weight": {"value": -26.801559194455454}}, {"from_seg": 10, "to_sr": 2, "weight": {"value": -26.801559194455454}}, {"from_seg": 11, "to_sr": 2, "weight": {"value": -26.801559194455454}}, {"from_seg": 12, "to_sr": 2, "weight": {"value": -26.801559194455454}}, {"from_seg": 13, "to_sr": 3, "weight": {"value": -26.801559194455454}}, {"from_seg": 14, "to_sr": 3, "weight": {"value": -26.801559194455454}}, {"from_seg": 15, "to_sr": 3, "weight": {"value": -26.801559194455454}}, {"from_seg": 16, "to_sr": 3, "weight": {"value": -26.801559194455454}}, {"from_seg": 17, "to_sr": 3, "weight": {"value": -26.801559194455454}}, {"from_seg": 18, "to_sr": 3, "weight": {"value": -26.801559194455454}}, {"from_seg": 19, "to_sr": 4, "weight": {"value": -26.801559194455454}}, {"from_seg": 20, "to_sr": 4, "weight": {"value": -26.801559194455454}}, {"from_seg": 21, "to_sr": 4, "weight": {"value": -26.801559194455454}}, {"from_seg": 22, "to_sr": 4, "weight": {"value": -26.801559194455454}}, {"from_seg": 23, "to_sr": 4, "weight": {"value": -26.801559194455454}}, {"from_seg": 24, "to_sr": 4, "weight": {"value": -26.801559194455454}}, {"from_seg": 25, "to_sr": 5, "weight": {"value": -26.801559194455454}}, {"from_seg": 26, "to_sr": 5, "weight": {"value": -26.801559194455454}}, {"from_seg": 27, "to_sr": 5, "weight": {"value": -26.801559194455454}}, {"from_seg": 28, "to_sr": 5, "weight": {"value": -26.801559194455454}}, {"from_seg": 29, "to_sr": 5, "weight": {"value": -26.801559194455454}}, {"from_seg": 30, "to_sr": 5, "weight": {"value": -26.801559194455454}}, {"from_seg": 31, "to_sr": 6, "weight": {"value": -26.801559194455454}}, {"from_seg": 32, "to_sr": 6, "weight": {"value": -26.801559194455454}}, {"from_seg": 33, "to_sr": 6, "weight": {"value": -26.801559194455454}}, {"from_seg": 34, "to_sr": 6, "weight": {"value": -26.801559194455454}}, {"from_seg": 35, "to_sr": 6, "weight": {"value": -26.801559194455454}}, {"from_seg": 36, "to_sr": 6, "weight": {"value": -26.801559194455454}}, {"from_seg": 37, "to_sr": 7, "weight": {"value": -26.801559194455454}}, {"from_seg": 38, "to_sr": 7, "weight": {"value": -26.801559194455454}}, {"from_seg": 39, "to_sr": 7, "weight": {"value": -26.801559194455454}}, {"from_seg": 40, "to_sr": 7, "weight": {"value": -26.801559194455454}}, {"from_seg": 41, "to_sr": 7, "weight": {"value": -26.801559194455454}}, {"from_seg": 42, "to_sr": 7, "weight": {"value": -26.801559194455454}}]}

Weights from dorsal stretch receptors to Nervous System:

In [13]:
print(json.dumps(json_data['stretch_receptor']['ns_d_weights']))

{"message": "Weights from dorsal SR to Nervous System", "value": [{"from_sr": 2, "to_ns": "DB_0", "weight": {"value": 1.0}}, {"from_sr": 3, "to_ns": "DB_1", "weight": {"value": 1.0}}, {"from_sr": 4, "to_ns": "DB_2", "weight": {"value": 1.0}}, {"from_sr": 5, "to_ns": "DB_3", "weight": {"value": 1.0}}, {"from_sr": 6, "to_ns": "DB_4", "weight": {"value": 1.0}}, {"from_sr": 7, "to_ns": "DB_5", "weight": {"value": 1.0}}, {"from_sr": 1, "to_ns": "SMDD_0", "weight": {"value": 1.0}}]}

In [14]:
print(json.dumps(json_data['stretch_receptor']['sr_vnc_gain']))

{"evotag": 14, "value": -160.80935516673273}

Almost any parameter (only those with a 'value' field which is a number) can be changed. This can be done directly in the JSON configuration file or via helper python scripts which are used to modify the JSON configuration file. To do this we need to force the worm model to initialize from the JSON configuration file. This is done by setting the "modelName" paramter to "W2DSR". Here we also include an "inputFolderName". In this case the initial JSON configuration file will be loaded from that directory, while a new directory, "outputFolderName" will be generated for the output results.

In [72]:
args = dict(
    modelFolder="Worm2D", #folder containing the compiled C++ binary code
    modelName="W2DSR",#rerun using the generic json loaded model
    inputFolderName=origFolderName, #input folder
    outputFolderName=outputFolderName, #output folder
    overwrite=True, #allow overwrite of output folder 
    randInitState=False, #use fixed initial conditions
    doTestRun=True, #run a single simple simulation
)

First, we can simply rerun the simulation using "W2DSR" potentially with different simulation parameters:

In [73]:
args['simduration']=30 #duration of simulation run
args['simtransient']=20 #transient of simulation run
args['doEvol'] = False #do not perform an optimization
run(**args) #the ExampleActivity.png and Motion.png figures must be reloaded above to see results

Directory 'notebooks/example_W2D18L_modified' already exists and the simulation results will be overwritten.
Parameter not found in worm_data.json
Parameter not found in worm_data.json
['Worm2D/main_osc', '--random_initial_state', '0', '--do_test_run', '1', '-R', '92108', '-p', '66', '-d', '50.0', '-t', '10.0', '--maxgens', '10', '-sd', '30', '-st', '20', '--doevol', '0', '-cpt', '1', '--dorandinit', '0', '--donml', '0', '--folder', 'notebooks/example_W2D18L_modified', '--modelname', 'W2DSR', '--domusc', '0', '-docpt', '1', '--evoType', 'Evo21']
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json

Loading activity data from: notebooks/example_W2D18L_modified/act.dat
Loading curvature data from: notebooks/example_W2D18L_modified/curv.dat
Loading body position data from: notebooks/example_W2D18L_modified/body.dat
Saved plot image to: notebooks/example_W2D18L_modified/ExampleActivity.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_3col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_4col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_av.png
Saved plot image to: notebooks/example_W2D18L_modified/FitnessHist.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages_2.png
Finished!

The model execution will overwrite the initial JSON file and some parts may be changed. Reload the new JSON configuration file after any execution is completed:

In [74]:
with open(outputFolderName + '/worm_data_worm.json') as json_file:
    new_json_data = json.load(json_file)

In [75]:
print(json.dumps(new_json_data['nervous_system']['cells']['VDA_1'], indent=2))

{
  "bias": {
    "evotag": 2,
    "value": -10.50067914566957
  },
  "cell_class": {
    "value": "vnc"
  },
  "gain": {
    "value": 1.0
  },
  "state": {
    "value": 0.2638888888888889
  },
  "tau": {
    "evotag": 4,
    "value": 0.6952001934027146
  }
}

Change a particular parameter.(Note: if the parameter changed is one that is set to be 'optimizable' so that it has an 'evotag' parameter next to the value field, then any change made here will have no effect if a further optimization is performed) :

In [76]:
new_json_data['nervous_system']['cells']['VDA_1']['bias']['value'] = 3
print(json.dumps(new_json_data['nervous_system']['cells']['VDA_1'], indent=2))

{
  "bias": {
    "evotag": 2,
    "value": 3
  },
  "cell_class": {
    "value": "vnc"
  },
  "gain": {
    "value": 1.0
  },
  "state": {
    "value": 0.2638888888888889
  },
  "tau": {
    "evotag": 4,
    "value": 0.6952001934027146
  }
}

The modified JSON needs to be re-saved to file before simulations are performed. To avoid changing the original JSON file, here we save the JSON configuration to the new output directory and make sure to unset the "inputFolderName" parameter so that simulations initialize from the new JSON (which will also subsequently be overwritten by the new simulation run).

In [78]:
args['inputFolderName']=None
with open(outputFolderName + '/worm_data_worm.json', "w") as f:
    json.dump(new_json_data, f)
run(**args)

Directory 'notebooks/example_W2D18L_modified' already exists and the simulation results will be overwritten.
Parameter not found in worm_data.json
Parameter not found in worm_data.json
Simulation parameters are the same as the existing ones, but overwrite is true so the simulation will be rerun.
['Worm2D/main_osc', '--random_initial_state', '0', '--do_test_run', '1', '-R', '92108', '-p', '66', '-d', '50.0', '-t', '10.0', '--maxgens', '10', '-sd', '30', '-st', '20', '--doevol', '0', '-cpt', '1', '--dorandinit', '0', '--donml', '0', '--folder', 'notebooks/example_W2D18L_modified', '--modelname', 'W2DSR', '--domusc', '0', '-docpt', '1', '--evoType', 'Evo21']
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json

Loading activity data from: notebooks/example_W2D18L_modified/act.dat
Loading curvature data from: notebooks/example_W2D18L_modified/curv.dat
Loading body position data from: notebooks/example_W2D18L_modified/body.dat
Saved plot image to: notebooks/example_W2D18L_modified/ExampleActivity.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_3col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_4col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_av.png
Saved plot image to: notebooks/example_W2D18L_modified/FitnessHist.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages_2.png
Finished!

Reload the new JSON file:

In [79]:
with open(outputFolderName + '/worm_data_worm.json') as json_file:
    new_json_data = json.load(json_file)
print(json.dumps(new_json_data['nervous_system']['cells']['VDA_1'], indent=2))

{
  "bias": {
    "evotag": 2,
    "value": 3.0
  },
  "cell_class": {
    "value": "vnc"
  },
  "gain": {
    "value": 1.0
  },
  "state": {
    "value": 0.2638888888888889
  },
  "tau": {
    "evotag": 4,
    "value": 0.6952001934027146
  }
}

In [80]:
JSON(new_json_data)

Although the simulation was not evolved and the value set was not evolvable anyway, the value change has not affected the simulation and is not set in the JSON after the simulation is performed:

Further optimizations can also be performed with the "W2DSR" model:

In [81]:
args['doEvol']=True #perform the optimization before running the simulation
args['maxGens']=10 #run the optimization for ten more generations 
args['popSize']=20 #population size for optimization
args['evoType']="Evo18" #the optimization function
print('Further generations to be added: ' + str(args['maxGens']))
run(**args)

Further generations to be added: 10
Directory 'notebooks/example_W2D18L_modified' already exists and all the contents will be overwritten.
Parameter not found in worm_data.json
Parameter not found in worm_data.json
['Worm2D/main_osc', '--random_initial_state', '0', '--do_test_run', '1', '-R', '92108', '-p', '20', '-d', '50.0', '-t', '10.0', '--maxgens', '10', '-sd', '30', '-st', '20', '--doevol', '1', '-cpt', '1', '--dorandinit', '0', '--donml', '0', '--folder', 'notebooks/example_W2D18L_modified', '--modelname', 'W2DSR', '--domusc', '0', '-docpt', '1', '--evoType', 'Evo18']
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
construct from CPT notebooks/example_W2D18L_modified/search.cpt with size 30
setting  population size to cpt population size: 66
Resuming search
jsonfile notebooks/example_W2D18L_modified/worm_data_evo.json
jsonfile notebooks/example_W2D18L_modified/worm_data_evo.json
jsonfile notebooks/example_W2D18L_modified/worm_data_evo.json

Loading activity data from: notebooks/example_W2D18L_modified/act.dat
Loading curvature data from: notebooks/example_W2D18L_modified/curv.dat
Loading body position data from: notebooks/example_W2D18L_modified/body.dat
Saved plot image to: notebooks/example_W2D18L_modified/ExampleActivity.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_3col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_4col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_av.png
Saved plot image to: notebooks/example_W2D18L_modified/FitnessHist.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages_2.png
Finished!

Because an evolution has been performed the value we set will have been overwritten:

In [82]:
with open(outputFolderName + '/worm_data_worm.json') as json_file:
    new_json_data = json.load(json_file)
print(json.dumps(new_json_data['nervous_system']['cells']['VDA_1'], indent=2))

{
  "bias": {
    "evotag": 2,
    "value": -11.506490527494137
  },
  "cell_class": {
    "value": "vnc"
  },
  "gain": {
    "value": 1.0
  },
  "state": {
    "value": 0.2638888888888889
  },
  "tau": {
    "evotag": 4,
    "value": 0.7807172035577956
  }
}

In the above evolution although the "popSize" parameter was set to 10 this was ignored by the actual execution because a checkpoint CPT file was found in the directory. To force the model to use the reduced "popSize" we need to set the "doCPT" parameter to false. In this case the entire worm population is initialized from the best fit worm parameter values which are stored in the JSON file:

In [23]:
args['doEvol']=True #perform the optimization before running the simulation
args['maxGens']=10 #run the optimization for ten more generations 
args['popSize']=20 #population size for optimization
args["doCPT"]=False
args['evoType']="Evo18" #the optimization function
print('Further generations to be added: ' + str(args['maxGens']))
run(**args)

Further generations to be added: 10
Directory 'notebooks/example_W2D18L_modified' already exists and all the contents will be overwritten.
Parameter not found in worm_data.json
Parameter not found in worm_data.json
['Worm2D/main_osc', '--random_initial_state', '0', '--do_test_run', '1', '-R', '92108', '-p', '20', '-d', '50.0', '-t', '10.0', '--maxgens', '10', '-sd', '30', '-st', '20', '--doevol', '1', '-cpt', '1', '--dorandinit', '0', '--donml', '0', '--folder', 'notebooks/example_W2D18L_modified', '--modelname', 'W2DSR', '--domusc', '0', '-docpt', '0', '--evoType', 'Evo18']
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
construct from best gene notebooks/example_W2D18L_modified/best.gen.dat with gene size 30
jsonfile notebooks/example_W2D18L_modified/worm_data_evo.json
jsonfile notebooks/example_W2D18L_modified/worm_data_evo.json
jsonfile notebooks/example_W2D18L_modified/worm_data_evo.json

Loading activity data from: notebooks/example_W2D18L_modified/act.dat
Loading curvature data from: notebooks/example_W2D18L_modified/curv.dat
Loading body position data from: notebooks/example_W2D18L_modified/body.dat
Saved plot image to: notebooks/example_W2D18L_modified/ExampleActivity.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_3col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_4col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_av.png
Saved plot image to: notebooks/example_W2D18L_modified/FitnessHist.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages_2.png
Finished!

In [24]:
args['doEvol']=True #perform the optimization before running the simulation
args['maxGens']=10 #run the optimization for ten more generations 
args['popSize']=70 #population size for optimization
args["doCPT"]=False
args['evoType']="Evo18" #the optimization function
print('Further generations to be added: ' + str(args['maxGens']))
run(**args)

Further generations to be added: 10
Directory 'notebooks/example_W2D18L_modified' already exists and all the contents will be overwritten.
Parameter not found in worm_data.json
Parameter not found in worm_data.json
['Worm2D/main_osc', '--random_initial_state', '0', '--do_test_run', '1', '-R', '92108', '-p', '70', '-d', '50.0', '-t', '10.0', '--maxgens', '10', '-sd', '30', '-st', '20', '--doevol', '1', '-cpt', '1', '--dorandinit', '0', '--donml', '0', '--folder', 'notebooks/example_W2D18L_modified', '--modelname', 'W2DSR', '--domusc', '0', '-docpt', '0', '--evoType', 'Evo18']
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
construct from best gene notebooks/example_W2D18L_modified/best.gen.dat with gene size 30
jsonfile notebooks/example_W2D18L_modified/worm_data_evo.json
jsonfile notebooks/example_W2D18L_modified/worm_data_evo.json
jsonfile notebooks/example_W2D18L_modified/worm_data_evo.json

Loading activity data from: notebooks/example_W2D18L_modified/act.dat
Loading curvature data from: notebooks/example_W2D18L_modified/curv.dat
Loading body position data from: notebooks/example_W2D18L_modified/body.dat
Saved plot image to: notebooks/example_W2D18L_modified/ExampleActivity.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_3col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_4col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_av.png
Saved plot image to: notebooks/example_W2D18L_modified/FitnessHist.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages_2.png
Finished!

When doCPT is set again the evolution will resume from the last checkpoint file, which here has a population size of 70 according to the last evolutionary simulation:

In [25]:
args['doEvol']=True #perform the optimization before running the simulation
args['maxGens']=10 #run the optimization for ten more generations 
args['popSize']=40 #population size for optimization
args["doCPT"]=True
args['evoType']="Evo18" #the optimization function
print('Further generations to be added: ' + str(args['maxGens']))
run(**args)

Further generations to be added: 10
Directory 'notebooks/example_W2D18L_modified' already exists and all the contents will be overwritten.
Parameter not found in worm_data.json
Parameter not found in worm_data.json
['Worm2D/main_osc', '--random_initial_state', '0', '--do_test_run', '1', '-R', '92108', '-p', '40', '-d', '50.0', '-t', '10.0', '--maxgens', '10', '-sd', '30', '-st', '20', '--doevol', '1', '-cpt', '1', '--dorandinit', '0', '--donml', '0', '--folder', 'notebooks/example_W2D18L_modified', '--modelname', 'W2DSR', '--domusc', '0', '-docpt', '1', '--evoType', 'Evo18']
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
construct from CPT notebooks/example_W2D18L_modified/search.cpt with size 30
setting  population size to cpt population size: 70
Resuming search
jsonfile notebooks/example_W2D18L_modified/worm_data_evo.json
jsonfile notebooks/example_W2D18L_modified/worm_data_evo.json
jsonfile notebooks/example_W2D18L_modified/worm_data_evo.json

Loading activity data from: notebooks/example_W2D18L_modified/act.dat
Loading curvature data from: notebooks/example_W2D18L_modified/curv.dat
Loading body position data from: notebooks/example_W2D18L_modified/body.dat
Saved plot image to: notebooks/example_W2D18L_modified/ExampleActivity.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_3col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_4col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_av.png
Saved plot image to: notebooks/example_W2D18L_modified/FitnessHist.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages_2.png
Finished!

In [83]:
with open(outputFolderName + '/worm_data_worm.json') as json_file:
    new_json_data = json.load(json_file)
print(json.dumps(new_json_data['stretch_receptor']['d_weights']))

{"message": "Weights from body segments to dorsal SR", "value": [{"from_seg": 7, "to_sr": 1, "weight": {"value": -8.59778170419639}}, {"from_seg": 8, "to_sr": 1, "weight": {"value": -8.59778170419639}}, {"from_seg": 9, "to_sr": 1, "weight": {"value": -8.59778170419639}}, {"from_seg": 10, "to_sr": 1, "weight": {"value": -8.59778170419639}}, {"from_seg": 11, "to_sr": 1, "weight": {"value": -8.59778170419639}}, {"from_seg": 12, "to_sr": 1, "weight": {"value": -8.59778170419639}}, {"from_seg": 13, "to_sr": 1, "weight": {"value": -8.59778170419639}}, {"from_seg": 14, "to_sr": 1, "weight": {"value": -8.59778170419639}}, {"from_seg": 15, "to_sr": 1, "weight": {"value": -8.59778170419639}}, {"from_seg": 16, "to_sr": 1, "weight": {"value": -8.59778170419639}}, {"from_seg": 17, "to_sr": 1, "weight": {"value": -8.59778170419639}}, {"from_seg": 18, "to_sr": 1, "weight": {"value": -8.59778170419639}}, {"from_seg": 19, "to_sr": 1, "weight": {"value": -8.59778170419639}}, {"from_seg": 20, "to_sr": 1, "weight": {"value": -8.59778170419639}}, {"from_seg": 7, "to_sr": 2, "weight": {"value": -26.683438106385438}}, {"from_seg": 8, "to_sr": 2, "weight": {"value": -26.683438106385438}}, {"from_seg": 9, "to_sr": 2, "weight": {"value": -26.683438106385438}}, {"from_seg": 10, "to_sr": 2, "weight": {"value": -26.683438106385438}}, {"from_seg": 11, "to_sr": 2, "weight": {"value": -26.683438106385438}}, {"from_seg": 12, "to_sr": 2, "weight": {"value": -26.683438106385438}}, {"from_seg": 13, "to_sr": 3, "weight": {"value": -26.683438106385438}}, {"from_seg": 14, "to_sr": 3, "weight": {"value": -26.683438106385438}}, {"from_seg": 15, "to_sr": 3, "weight": {"value": -26.683438106385438}}, {"from_seg": 16, "to_sr": 3, "weight": {"value": -26.683438106385438}}, {"from_seg": 17, "to_sr": 3, "weight": {"value": -26.683438106385438}}, {"from_seg": 18, "to_sr": 3, "weight": {"value": -26.683438106385438}}, {"from_seg": 19, "to_sr": 4, "weight": {"value": -26.683438106385438}}, {"from_seg": 20, "to_sr": 4, "weight": {"value": -26.683438106385438}}, {"from_seg": 21, "to_sr": 4, "weight": {"value": -26.683438106385438}}, {"from_seg": 22, "to_sr": 4, "weight": {"value": -26.683438106385438}}, {"from_seg": 23, "to_sr": 4, "weight": {"value": -26.683438106385438}}, {"from_seg": 24, "to_sr": 4, "weight": {"value": -26.683438106385438}}, {"from_seg": 25, "to_sr": 5, "weight": {"value": -26.683438106385438}}, {"from_seg": 26, "to_sr": 5, "weight": {"value": -26.683438106385438}}, {"from_seg": 27, "to_sr": 5, "weight": {"value": -26.683438106385438}}, {"from_seg": 28, "to_sr": 5, "weight": {"value": -26.683438106385438}}, {"from_seg": 29, "to_sr": 5, "weight": {"value": -26.683438106385438}}, {"from_seg": 30, "to_sr": 5, "weight": {"value": -26.683438106385438}}, {"from_seg": 31, "to_sr": 6, "weight": {"value": -26.683438106385438}}, {"from_seg": 32, "to_sr": 6, "weight": {"value": -26.683438106385438}}, {"from_seg": 33, "to_sr": 6, "weight": {"value": -26.683438106385438}}, {"from_seg": 34, "to_sr": 6, "weight": {"value": -26.683438106385438}}, {"from_seg": 35, "to_sr": 6, "weight": {"value": -26.683438106385438}}, {"from_seg": 36, "to_sr": 6, "weight": {"value": -26.683438106385438}}, {"from_seg": 37, "to_sr": 7, "weight": {"value": -26.683438106385438}}, {"from_seg": 38, "to_sr": 7, "weight": {"value": -26.683438106385438}}, {"from_seg": 39, "to_sr": 7, "weight": {"value": -26.683438106385438}}, {"from_seg": 40, "to_sr": 7, "weight": {"value": -26.683438106385438}}, {"from_seg": 41, "to_sr": 7, "weight": {"value": -26.683438106385438}}, {"from_seg": 42, "to_sr": 7, "weight": {"value": -26.683438106385438}}]}

In [84]:
print(json.dumps(new_json_data['stretch_receptor']['d_weights']['value'][3]))
new_json_data['stretch_receptor']['d_weights']['value'][3]['weight']['value']=3
print(json.dumps(new_json_data['stretch_receptor']['d_weights']['value'][3]))

{"from_seg": 10, "to_sr": 1, "weight": {"value": -8.59778170419639}}
{"from_seg": 10, "to_sr": 1, "weight": {"value": 3}}

In [85]:
args['inputFolderName']=None
with open(outputFolderName + '/worm_data_worm.json', "w") as f:
    json.dump(new_json_data, f)
args['simduration']=20 #duration of simulation run
args['simtransient']=10 #transient of simulation run
args['doEvol'] = False #do not perform an optimization
run(**args) #the ExampleActivity.png and Motion.png figures must be reloaded above to see results

Directory 'notebooks/example_W2D18L_modified' already exists and the simulation results will be overwritten.
Parameter not found in worm_data.json
Parameter not found in worm_data.json
['Worm2D/main_osc', '--random_initial_state', '0', '--do_test_run', '1', '-R', '92108', '-p', '20', '-d', '50.0', '-t', '10.0', '--maxgens', '10', '-sd', '20', '-st', '10', '--doevol', '0', '-cpt', '1', '--dorandinit', '0', '--donml', '0', '--folder', 'notebooks/example_W2D18L_modified', '--modelname', 'W2DSR', '--domusc', '0', '-docpt', '1', '--evoType', 'Evo18']
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json

Loading activity data from: notebooks/example_W2D18L_modified/act.dat
Loading curvature data from: notebooks/example_W2D18L_modified/curv.dat
Loading body position data from: notebooks/example_W2D18L_modified/body.dat
Saved plot image to: notebooks/example_W2D18L_modified/ExampleActivity.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_3col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_4col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_av.png
Saved plot image to: notebooks/example_W2D18L_modified/FitnessHist.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages_2.png
Finished!

Although the simulation was not evolved and the value set was not evolvable anyway, the value change has not affected the simulation and is not set in the JSON after the simulation is performed:

In [86]:
with open(outputFolderName + '/worm_data_worm.json') as json_file:
    new_json_data = json.load(json_file)
print(json.dumps(new_json_data['stretch_receptor']['d_weights']['value'][3]))

{"from_seg": 10, "to_sr": 1, "weight": {"value": -8.59778170419639}}

This is because the stretch_receptor was generated from the optimizable parameters, "sr_head_gain" and "sr_vnc_gain".The stretch_receptor includes the field, "set_direct":

In [88]:
pd.DataFrame({"stretch receptor keys": new_json_data["stretch_receptor"].keys()})

   stretch receptor keys
0              d_weights
1                 n_segs
2              n_stretch
3           ns_d_weights
4           ns_v_weights
5              plot_size
6             set_direct
7           sr_head_gain
8             sr_head_sr
9            sr_vnc_gain
10             sr_vnc_sr
11                  type
12             v_weights

In [89]:
print(json.dumps(new_json_data['stretch_receptor']['set_direct']))

{"value": false}

To force the Worm2D to load directly from the stretch receptor structure, set this parameter to true:

In [90]:
new_json_data['stretch_receptor']['set_direct']['value']= True
new_json_data['stretch_receptor']['d_weights']['value'][3]['weight']['value']=3
args['inputFolderName']=None
with open(outputFolderName + '/worm_data_worm.json', "w") as f:
    json.dump(new_json_data, f)
run(**args)

Directory 'notebooks/example_W2D18L_modified' already exists and the simulation results will be overwritten.
Parameter not found in worm_data.json
Parameter not found in worm_data.json
Simulation parameters are the same as the existing ones, but overwrite is true so the simulation will be rerun.
['Worm2D/main_osc', '--random_initial_state', '0', '--do_test_run', '1', '-R', '92108', '-p', '20', '-d', '50.0', '-t', '10.0', '--maxgens', '10', '-sd', '20', '-st', '10', '--doevol', '0', '-cpt', '1', '--dorandinit', '0', '--donml', '0', '--folder', 'notebooks/example_W2D18L_modified', '--modelname', 'W2DSR', '--domusc', '0', '-docpt', '1', '--evoType', 'Evo18']
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json

Error:
terminate called after throwing an instance of 'nlohmann::detail::out_of_range'
  what():  [json.exception.out_of_range.403] key 'ns_d_weights' not found

SystemExit: -6

/home/adam/miniconda3/envs/celoc_env/lib/python3.12/site-packages/IPython/core/interactiveshell.py:3678: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

In [26]:
args['simduration']=20 #duration of simulation run
args['simtransient']=10 #transient of simulation run
args['doEvol'] = False #do not perform an optimization
run(**args) #the ExampleActivity.png and Motion.png figures must be reloaded above to see results

Directory 'notebooks/example_W2D18L_modified' already exists and the simulation results will be overwritten.
Parameter not found in worm_data.json
Parameter not found in worm_data.json
['Worm2D/main_osc', '--random_initial_state', '0', '--do_test_run', '1', '-R', '92108', '-p', '40', '-d', '50.0', '-t', '10.0', '--maxgens', '10', '-sd', '20', '-st', '10', '--doevol', '0', '-cpt', '1', '--dorandinit', '0', '--donml', '0', '--folder', 'notebooks/example_W2D18L_modified', '--modelname', 'W2DSR', '--domusc', '0', '-docpt', '1', '--evoType', 'Evo18']
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json
jsonfile notebooks/example_W2D18L_modified/worm_data_worm.json

Loading activity data from: notebooks/example_W2D18L_modified/act.dat
Loading curvature data from: notebooks/example_W2D18L_modified/curv.dat
Loading body position data from: notebooks/example_W2D18L_modified/body.dat
Saved plot image to: notebooks/example_W2D18L_modified/ExampleActivity.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_3col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_legend_4col.png
Saved plot image to: notebooks/example_W2D18L_modified/EvoHist_av.png
Saved plot image to: notebooks/example_W2D18L_modified/FitnessHist.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages.png
Saved plot image to: notebooks/example_W2D18L_modified/Evolution_averages_2.png
Finished!